
// This file is automatically generated. Do not edit it directly.

export const setupWorkoutFunctions = async (supabase: any) => {
  // Create function to record completed workouts
  await supabase.rpc('record_completed_workout', {
    workout_id_param: '00000000-0000-0000-0000-000000000000',
    duration_param: 0
  }).catch(() => {
    // Function likely already exists, this is just to ensure it's callable
    console.log('record_completed_workout function already exists');
  });
  
  // Create function to get completed workouts since a date
  await supabase.rpc('get_completed_workouts_since', {
    start_date: new Date().toISOString()
  }).catch(() => {
    // Function likely already exists, this is just to ensure it's callable
    console.log('get_completed_workouts_since function already exists');
  });
  
  // Create function to get trained muscles since a date
  await supabase.rpc('get_trained_muscles_since', {
    start_date: new Date().toISOString()
  }).catch(() => {
    // Function likely already exists, this is just to ensure it's callable
    console.log('get_trained_muscles_since function already exists');
  });
};
